import { MigrationInterface, QueryRunner } from "typeorm";

export class AddGenres1755485255956 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO genres (id, name, created_at, updated_at)
      VALUES
        (UUID(), 'Adventure', NOW(), NOW()),
        (UUID(), 'Martial Arts / Kung Fu', NOW(), NOW()),
        (UUID(), 'Superhero', NOW(), NOW()),
        (UUID(), 'Spy / Espionage', NOW(), NOW()),
        (UUID(), 'War', NOW(), NOW()),
        (UUID(), 'Slapstick', NOW(), NOW()),
        (UUID(), 'Romantic Comedy (Rom-Com)', NOW(), NOW()),
        (UUID(), 'Dark Comedy / Black Comedy', NOW(), NOW()),
        (UUID(), 'Satire / Parody', NOW(), NOW()),
        (UUID(), 'Sitcom (TV-specific)', NOW(), NOW()),
        (UUID(), 'Crime / Mafia / Gangster', NOW(), NOW()),
        (UUID(), 'Historical Drama', NOW(), NOW()),
        (UUID(), 'Legal / Courtroom Drama', NOW(), NOW()),
        (UUID(), 'Political Drama', NOW(), NOW()),
        (UUID(), 'Medical Drama', NOW(), NOW()),
        (UUID(), 'Family / Coming-of-Age', NOW(), NOW()),
        (UUID(), 'Psychological Horror', NOW(), NOW()),
        (UUID(), 'Slasher', NOW(), NOW()),
        (UUID(), 'Supernatural / Paranormal', NOW(), NOW()),
        (UUID(), 'Thriller / Suspense', NOW(), NOW()),
        (UUID(), 'Mystery / Detective', NOW(), NOW()),
        (UUID(), 'Science Fiction & Fantasy', NOW(), NOW()),
        (UUID(), 'Sci-Fi (general)', NOW(), NOW()),
        (UUID(), 'Space Opera', NOW(), NOW()),
        (UUID(), 'Dystopian / Post-Apocalyptic', NOW(), NOW()),
        (UUID(), 'Cyberpunk', NOW(), NOW()),
        (UUID(), 'Supernatural Fantasy', NOW(), NOW()),
        (UUID(), 'High Fantasy / Epic Fantasy', NOW(), NOW()),
        (UUID(), 'Romance', NOW(), NOW()),
        (UUID(), 'Romance (general)', NOW(), NOW()),
        (UUID(), 'Period Romance', NOW(), NOW()),
        (UUID(), 'Romantic Drama', NOW(), NOW()),
        (UUID(), 'Animation & Kids', NOW(), NOW()),
        (UUID(), 'Animated Feature', NOW(), NOW()),
        (UUID(), 'Anime', NOW(), NOW()),
        (UUID(), 'Family / Kids', NOW(), NOW()),
        (UUID(), 'Stop-Motion', NOW(), NOW()),
        (UUID(), 'Documentary & Non-Fiction', NOW(), NOW()),
        (UUID(), 'Documentary', NOW(), NOW()),
        (UUID(), 'Biographical (Biopic)', NOW(), NOW()),
        (UUID(), 'True Crime', NOW(), NOW()),
        (UUID(), 'Nature / Wildlife', NOW(), NOW()),
        (UUID(), 'Musical & Performance', NOW(), NOW()),
        (UUID(), 'Musical', NOW(), NOW()),
        (UUID(), 'Dance / Performance', NOW(), NOW()),
        (UUID(), 'Concert Film', NOW(), NOW()),
        (UUID(), 'Experimental & MiscellaneOus', NOW(), NOW()),
        (UUID(), 'Art House / Indie', NOW(), NOW()),
        (UUID(), 'Noir / Neo-Noir', NOW(), NOW()),
        (UUID(), 'Anthology / Episodic', NOW(), NOW()),
        (UUID(), 'Disaster', NOW(), NOW()),
        (UUID(), 'Heist / Caper', NOW(), NOW()),
        (UUID(), 'Survival', NOW(), NOW()),
        (UUID(), 'Pirate', NOW(), NOW()),
        (UUID(), 'Western / Neo-Western', NOW(), NOW()),
        (UUID(), 'Sports Action', NOW(), NOW()),
        (UUID(), 'Comedy Subgenres', NOW(), NOW()),
        (UUID(), 'Gross-out', NOW(), NOW()),
        (UUID(), 'Workplace Comedy', NOW(), NOW()),
        (UUID(), 'Buddy Comedy', NOW(), NOW()),
        (UUID(), 'Teen Comedy', NOW(), NOW()),
        (UUID(), 'Romantic Parody', NOW(), NOW()),
        (UUID(), 'Drama Subgenres', NOW(), NOW()),
        (UUID(), 'Melodrama', NOW(), NOW()),
        (UUID(), 'Soap Opera', NOW(), NOW()),
        (UUID(), 'Tragedy', NOW(), NOW()),
        (UUID(), 'Coming-of-Age', NOW(), NOW()),
        (UUID(), 'Psychological Drama', NOW(), NOW()),
        (UUID(), 'Horror / Thriller Subgenres', NOW(), NOW()),
        (UUID(), 'Body Horror', NOW(), NOW()),
        (UUID(), 'Gothic Horror', NOW(), NOW()),
        (UUID(), 'Monster Horror (vampires, zombies, werewolves)', NOW(), NOW()),
        (UUID(), 'Survival Horror', NOW(), NOW()),
        (UUID(), 'Eco-Horror / Nature Horror', NOW(), NOW()),
        (UUID(), 'Techno-Thriller', NOW(), NOW()),
        (UUID(), 'Sci-Fi / Fantasy Subgenres', NOW(), NOW()),
        (UUID(), 'Time Travel', NOW(), NOW()),
        (UUID(), 'Alien Invasion', NOW(), NOW()),
        (UUID(), 'Steampunk', NOW(), NOW()),
        (UUID(), 'Sword and Sorcery', NOW(), NOW()),
        (UUID(), 'Magical Realism', NOW(), NOW()),
        (UUID(), 'Superhero Fantasy', NOW(), NOW()),
        (UUID(), 'Romance Subgenres', NOW(), NOW()),
        (UUID(), 'Love Triangle', NOW(), NOW()),
        (UUID(), 'Forbidden Romance', NOW(), NOW()),
        (UUID(), 'Romantic Fantasy', NOW(), NOW()),
        (UUID(), 'Historical Romance', NOW(), NOW()),
        (UUID(), 'Animation Subgenres', NOW(), NOW()),
        (UUID(), 'Adult Animation', NOW(), NOW()),
        (UUID(), 'Animated Horror', NOW(), NOW()),
        (UUID(), 'Adventure Animation', NOW(), NOW()),
        (UUID(), 'Comedy Animation', NOW(), NOW()),
        (UUID(), 'Mecha', NOW(), NOW()),
        (UUID(), 'Shonen', NOW(), NOW()),
        (UUID(), 'Shojo', NOW(), NOW()),
        (UUID(), 'Isekai', NOW(), NOW()),
        (UUID(), 'Documentary / Non-Fiction', NOW(), NOW()),
        (UUID(), 'Travelogue', NOW(), NOW()),
        (UUID(), 'Political Documentary', NOW(), NOW()),
        (UUID(), 'Investigative / Exposé', NOW(), NOW()),
        (UUID(), 'Historical Reenactment', NOW(), NOW()),
        (UUID(), 'Sports Documentary', NOW(), NOW()),
        (UUID(), 'Musical / Performance Subgenres', NOW(), NOW()),
        (UUID(), 'Opera Film', NOW(), NOW()),
        (UUID(), 'Rockumentary', NOW(), NOW()),
        (UUID(), 'Dance Musical', NOW(), NOW()),
        (UUID(), 'Stage-to-Film Adaptation', NOW(), NOW()),
        (UUID(), 'Other / Miscellaneous', NOW(), NOW()),
        (UUID(), 'Experimental / Avant-Garde', NOW(), NOW()),
        (UUID(), 'Mockumentary', NOW(), NOW()),
        (UUID(), 'Found Footage', NOW(), NOW()),
        (UUID(), 'Anthology', NOW(), NOW()),
        (UUID(), 'Espionage Thriller', NOW(), NOW())
  `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM genres
      WHERE name IN ('Adventure', 'Martial Arts / Kung Fu', 'Superhero', 'Spy / Espionage', 'War', 'Slapstick', 'Romantic Comedy (Rom-Com)', 'Dark Comedy / Black Comedy', 'Satire / Parody', 'Sitcom (TV-specific)', 'Crime / Mafia / Gangster', 'Historical Drama', 'Legal / Courtroom Drama', 'Political Drama', 'Medical Drama', 'Family / Coming-of-Age', 'Psychological Horror', 'Slasher', 'Supernatural / Paranormal', 'Thriller / Suspense', 'Mystery / Detective', 'Science Fiction & Fantasy', 'Sci-Fi (general)', 'Space Opera', 'Dystopian / Post-Apocalyptic', 'Cyberpunk', 'Supernatural Fantasy', 'High Fantasy / Epic Fantasy', 'Romance', 'Romance (general)', 'Period Romance', 'Romantic Drama', 'Animation & Kids', 'Animated Feature', 'Anime', 'Family / Kids', 'Stop-Motion', 'Documentary & Non-Fiction', 'Documentary', 'Biographical (Biopic)', 'True Crime', 'Nature / Wildlife', 'Musical & Performance', 'Musical', 'Dance / Performance', 'Concert Film', 'Experimental & MiscellaneOus', 'Art House / Indie', 'Mockumentary', 'Anthology / Episodic', 'Disaster', 'Heist / Caper', 'Survival', 'Pirate', 'Western / Neo-Western', 'Sports Action', 'Comedy Subgenres', 'Gross-out', 'Workplace Comedy', 'Buddy Comedy', 'Teen Comedy', 'Romantic Parody', 'Drama Subgenres', 'Melodrama', 'Soap Opera', 'Tragedy', 'Coming-of-Age', 'Psychological Drama', 'Horror / Thriller Subgenres', 'Body Horror', 'Gothic Horror', 'Monster Horror (vampires, zombies, werewolves)', 'Survival Horror', 'Eco-Horror / Nature Horror', 'Techno-Thriller', 'Sci-Fi / Fantasy Subgenres', 'Time Travel', 'Alien Invasion', 'Steampunk', 'Sword and Sorcery', 'Magical Realism', 'Superhero Fantasy', 'Romance Subgenres', 'Love Triangle', 'Forbidden Romance', 'Romantic Fantasy', 'Historical Romance', 'Animation Subgenres', 'Adult Animation', 'Animated Horror', 'Adventure Animation', 'Comedy Animation', 'Mecha', 'Shonen', 'Shojo', 'Isekai', 'Documentary / Non-Fiction', 'Travelogue', 'Political Documentary', 'Investigative / Exposé', 'Historical Reenactment', 'Sports Documentary', 'Musical / Performance Subgenres', 'Opera Film', 'Rockumentary', 'Dance Musical', 'Stage-to-Film Adaptation', 'Other / Miscellaneous', 'Experimental / Avant-Garde', 'Found Footage', 'Anthology', 'Noir / Neo-Noir', 'Espionage Thriller')
  `);
  }
}
