import { AppDataSource } from "../data-source";
import { Genre } from "../entities";
import { Seed } from "./seed";

// eslint-disable-next-line import/no-default-export
export default class AddGenres1755299375376 implements Seed {
  async run() {
    const repo = AppDataSource.getRepository(Genre);

    await repo.upsert(
      [
        { name: "Action" },
        { name: "Comedy" },
        { name: "Drama" },
        { name: "Horror" },
        { name: "Adventure" },
        { name: "Martial Arts / Kung Fu" },
        { name: "Superhero" },
        { name: "Spy / Espionage" },
        { name: "War" },
        { name: "Slapstick" },
        { name: "Romantic Comedy (Rom-Com)" },
        { name: "Dark Comedy / Black Comedy" },
        { name: "Satire / Parody" },
        { name: "Sitcom (TV-specific)" },
        { name: "Crime / Mafia / Gangster" },
        { name: "Historical Drama" },
        { name: "Legal / Courtroom Drama" },
        { name: "Political Drama" },
        { name: "Medical Drama" },
        { name: "Family / Coming-of-Age" },
        { name: "Psychological Horror" },
        { name: "Slasher" },
        { name: "Supernatural / Paranormal" },
        { name: "Thriller / Suspense" },
        { name: "Mystery / Detective" },
        { name: "Science Fiction & Fantasy" },
        { name: "Sci-Fi (general)" },
        { name: "Space Opera" },
        { name: "Dystopian / Post-Apocalyptic" },
        { name: "Cyberpunk" },
        { name: "Supernatural Fantasy" },
        { name: "High Fantasy / Epic Fantasy" },
        { name: "Romance" },
        { name: "Romance (general)" },
        { name: "Period Romance" },
        { name: "Romantic Drama" },
        { name: "Animation & Kids" },
        { name: "Animated Feature" },
        { name: "Anime" },
        { name: "Family / Kids" },
        { name: "Stop-Motion" },
        { name: "Documentary & Non-Fiction" },
        { name: "Documentary" },
        { name: "Biographical (Biopic)" },
        { name: "True Crime" },
        { name: "Nature / Wildlife" },
        { name: "Musical & Performance" },
        { name: "Musical" },
        { name: "Dance / Performance" },
        { name: "Concert Film" },
        { name: "Experimental & MiscellaneOus" },
        { name: "Art House / Indie" },
        { name: "Noir / Neo-Noir" },
        { name: "Anthology / Episodic" },
        { name: "Disaster" },
        { name: "Heist / Caper" },
        { name: "Survival" },
        { name: "Pirate" },
        { name: "Western / Neo-Western" },
        { name: "Sports Action" },
        { name: "Comedy Subgenres" },
        { name: "Gross-out" },
        { name: "Workplace Comedy" },
        { name: "Buddy Comedy" },
        { name: "Teen Comedy" },
        { name: "Romantic Parody" },
        { name: "Drama Subgenres" },
        { name: "Melodrama" },
        { name: "Soap Opera" },
        { name: "Tragedy" },
        { name: "Coming-of-Age" },
        { name: "Psychological Drama" },
        { name: "Horror / Thriller Subgenres" },
        { name: "Body Horror" },
        { name: "Gothic Horror" },
        { name: "Monster Horror (vampires, zombies, werewolves)" },
        { name: "Survival Horror" },
        { name: "Eco-Horror / Nature Horror" },
        { name: "Techno-Thriller" },
        { name: "Sci-Fi / Fantasy Subgenres" },
        { name: "Time Travel" },
        { name: "Alien Invasion" },
        { name: "Steampunk" },
        { name: "Sword and Sorcery" },
        { name: "Magical Realism" },
        { name: "Superhero Fantasy" },
        { name: "Romance Subgenres" },
        { name: "Love Triangle" },
        { name: "Forbidden Romance" },
        { name: "Romantic Fantasy" },
        { name: "Historical Romance" },
        { name: "Animation Subgenres" },
        { name: "Adult Animation" },
        { name: "Animated Horror" },
        { name: "Adventure Animation" },
        { name: "Comedy Animation" },
        { name: "Mecha" },
        { name: "Shonen" },
        { name: "Shojo" },
        { name: "Isekai" },
        { name: "Documentary / Non-Fiction" },
        { name: "Travelogue" },
        { name: "Political Documentary" },
        { name: "Investigative / Exposé" },
        { name: "Historical Reenactment" },
        { name: "Sports Documentary" },
        { name: "Musical / Performance Subgenres" },
        { name: "Opera Film" },
        { name: "Rockumentary" },
        { name: "Dance Musical" },
        { name: "Stage-to-Film Adaptation" },
        { name: "Other / Miscellaneous" },
        { name: "Experimental / Avant-Garde" },
        { name: "Mockumentary" },
        { name: "Found Footage" },
        { name: "Anthology" },
        { name: "Espionage Thriller" },
      ],
      ["name"]
    );
  }
}
